application: telegram-list-bot
version: 1
runtime: python27
api_version: 1
# vm: true
# entrypoint: gunicorn -b :$PORT main:app
threadsafe: yes

# runtime_config:
#     python_version: 3

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /set_webhook
  login: admin
  script: main.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: PIL
  version: latest